### PR TITLE
Add warning that current marathon version is not support.

### PR DESCRIPTION
**Pull request by joerg84**

### CODE REVIEW

**Review by timcharper — APPROVED** [review]

**Comment by tobilg** [comment]
I think one can specify the Marathon version via a flag. Or does it no longer use JSONschema?

**Comment by joerg84** [comment]
@tobilg  the JSON schema for representing the API is deprecated according to @timcharper

**Comment by timcharper** [comment]
Yes, that's the problem. Marathon does not use JSON schema, it uses RAML.

In order to get this tool working, we would either need to:

* Have the tool read the RAML API definition, rather than JSON schema
* create a tool that generates JSON schema from the RAML.

The latter ought to be possible, but, nobody has spent the time doing it.

We still have JSON schema in the Marathon repository, however, it is out of date.

**Comment by joerg84** [comment]
Should we ask the community whether someone is interested?

**Comment by tobilg** [comment]
I see. It was removed before once and added again in the past, but I totally understand you don’t maintain it anymore if you don’t need it. 

I don’t have the resources as well unfortunately. I’d suggest to add the last Marathon version which it is compatible with in the readme though.

**Comment by joerg84** [comment]
@tobilg I asked in the community (mesos slack #marathon) whether someone is interested in updating it. Will add the latest version once I have confirmed it. Thanks for all your contributions!

**Comment by timcharper** [comment]
This may be more feasible than I had previously thought.

https://github.com/raml-org/ramldt2jsonschema

If this tool works, then we could add a command to keep the JSON schema up to date. I think this might make some people happy.

**Comment by tobilg** [comment]
Sure, you’re welcome. Eventually https://github.com/raml-org/raml-js-parser-2 could be used to parse the RAML.

**Comment by tobilg** [comment]
I had a look at the link @timcharper provided. "Unfortunately", as Marathon RAMLs uses includes, https://github.com/raml-org/ramldt2jsonschema#dt2js-1 applies:

> NOTE: when the inputed RAML contains !includes and those includes are not in the same directory as the script it is being ran from, you can use dt2js.setBasePath() to specify a different base path.

That  means that it gets a lot more complicated to first download the wrapper, check for includes, download them locally, and only then convert the RAML to JSONschema...

**Comment by timcharper** [comment]
Yeah, I think this is something that we can do on the Marathon side :-)

**Comment by timcharper** [comment]
Yeah, switching to use the raml-js-parser-2 tool seems ideal. :-)

**Pull request merged**
